### PR TITLE
Ruby OOP Milestone 3: Tic Tac Toe

### PR DESCRIPTION
**Pull request by Flakster**
## This pull request includes:

- Files for the Game, Board and Player classes
- Interface module
- Game logic distributed into instance methods

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi @Flakster. Nice work:+1:. There is a little issue with your project :fast_forward:**

You have disabled a number of linter configs. You are not allowed to do that. Kindly find other workarounds to the linter errors rather than disabling them.




_**Kindly take care of the linter issue above and submit another code review request.**_

**Cheers:stars:**

### Status: Change Requested.

**Comment by Flakster** [comment]
## Requested changes have been done

- Biggest methods have been broken down into several others to decrease the individual complexity according to the Rubocop rules and good programming practices

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Great  work, Congratulation :+1: Project Approved.
You did all changes required previously. But your project will be better if you consider implementing next changes, before merging to develop:
#### [OPTIONAL]:
* No `puts/print` and `get.chomp` outside `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

* Use attr_readers/attr_writers instead of attr_accessors. It will allow writing that property from outside the class. That variable can be set to anything. <TODO: explain why> ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/attr_accessor.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

_Goodluck in your next project_ *Happy coding*

**Comment by Flakster** [comment]
@pelzolga123  your suggestions have been included in the project. thanks for your feedback

**Pull request merged**
